title: Treinamentos VERT
description: Portal para acesso aos treinamentos realizados pela equipe de TI da VERT.
# show_downloads: true

# baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://vert-capital.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty
